### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by wh-isper** [YonghengSun1997/ODADA#3]
作者，您好！我已经在google driver上申请了下载完整的数据集，请问什么时候可以访问？这些数据都是和data/datalist/.txt里面一样处理好的npy文件吗？

**Comment by YonghengSun1997** [comment]
现在可以下载了吗？data/datalist/.txt是心脏数据，google driver上只有前列腺数据

**Comment by lllzzzrrr** [comment]
我只是刚刚申请了，我也不知道能不能通过，我以为这是您审核的。那么请问想要完整复现论文的话，论文里实际使用的完整的数据集去哪里下载呢？我看githu上上传的HK和BIDMC的数据集只有十几张

**Comment by YonghengSun1997** [comment]
我刚刚修改了权限了，不需要通过，可以直接下载

**Comment by wh-isper** [comment]
我已经下载了，感谢您的分享！
