### ISSUE TITLE
关于UNet_DA的问题

### ISSUE THREAD

**Issue by qujunda123** [YonghengSun1997/ODADA#8]
我发现在您Unet_DA的实现中，将f_ds使用了梯度翻转层，即f_ds=self.grl(f_ds)。我猜测，此部分可以弄反了，应该是f_di=self.grl(f_di)？不知道是否应该这样？

**Comment by YonghengSun1997** [comment]
Thank you for figuring it out! We have made the modification. Actually, in our paper, we use DeepLab as our backbone. After the modification, the U-Net version might work better.

**Comment by qujunda123** [comment]
谢谢您的回复，我还有一个小问题，是不是应该f_di_reverse=self.grl(f_di)，以将f_di区分开。后续输入到分割模型中是不是应该是grl前的特征呢？

**Comment by qujunda123** [comment]
非常感谢您的回复！
