### ISSUE TITLE
关于模型训练的问题

### ISSUE THREAD

**Issue by qujunda** [YonghengSun1997/ODADA#9]
在您main.py的代码的670-674，您将名字中feature_extractor的层设置为不传梯度。但是似乎模型中没有feature_extractor的层，不知道是否出现了问题还是我的理解出错了

**Comment by YonghengSun1997** [comment]
feature_extractor是UNet_DA中的层。在deeplabv3_resnet50中，feature_extractor应该是backbone才对。谢谢你的提醒！

**Comment by qujunda** [comment]
好的，谢谢您。另外的一个问题是我发现我的正交损失一直是0，这可能是什么问题呢
